apiVersion: v1
kind: Pod
metadata:
  name: pod-linked-containers
spec:
  hostNetwork: true
  containers:
    - name: host-port-pods-app
      image: pbadhe34/my-apps:app2
      ports:
        - containerPort: 8090          
    - name: redis
      image: redis
      ports:
        - containerPort: 6379           
