apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-app
  labels:
    k8s-app: default-http-backend  
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: default-http-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-http-backend-container
        image: pbadhe34/my-apps:app1
        ports:
        - containerPort: 8090        
