apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: py-app-deployment-host
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: py-app
    spec:       
      containers:
      - name: py-app-container
        image: pbadhe34/my-apps:app1
        ports:
        - containerPort: 8090
          hostPort: 7070 
        env:
          - name: redis
            value: "redis"        